config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :clients
  root to: "users#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
    include CanCan::Ability
  
    def initialize(user)
  
      user ||= User.new # guest user
  
      if user.role == 'User'
        can :manage, User, id: user.id
        can :manage, Client, id: user.client_id
      elsif user.role == 'Admin'  # additional permissions for administrators
          can :manage, Client
          can :manage, User
      end
  
    end
  
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
  validates :first_name, :last_name, :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable

  ROLES = ["User", "Admin"]

  belongs_to :client, optional: true

  before_create :setup

  def full_name
    first_name + " " + last_name
  end

  def setup
    self.role ||= "User"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    skip_before_action :verify_authenticity_token, if: lambda { ENV["skip_authenticity_token"].present? }

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  load_and_authorize_resource

  # GET /clients or /clients.json
  def index
    #@clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :city, :address, :activated)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users or /users.json
  def index
    @users.includes(:client)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :role, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= form.label :activated %>
    <%= form.check_box :activated, class: "form-control" %>
  </div>


<button type="submit" class="btn btn-primary">Save</button>

<% end %>

app/views/clients/edit.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Editing Client</h1>
</div>

<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<p id="notice" class="alert" role="alert"><%= notice %></p>

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Clients</h1>
    <%= link_to 'New Client', new_client_path, class: "btn btn-primary" %>
</div>


<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Address</th>
      <th>Activated</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.city %></td>
        <td><%= client.address %></td>
        <td><%= client.activated %></td>
        <td>
          <%= link_to 'Show', client, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_client_path(client), class: "btn btn-primary" %>
          <%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">New Client</h1>
</div>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-striped">



<tr>
  <td>
    <strong>Name:</strong>
  </td>
  <td>
          <%= @client.name %>
      </td>
</tr>


<tr>
  <td>
    <strong>City:</strong>
  </td>
  <td>
          <%= @client.city %>
      </td>
</tr>


<tr>
  <td>
    <strong>Address:</strong>
  </td>
  <td>
          <%= @client.address %>
      </td>
</tr>


<tr>
  <td>
    <strong>Activated:</strong>
  </td>
  <td>
          <%= @client.activated %>
      </td>
</tr>


</table> 

<div class="action">
  <%= link_to 'Edit', edit_client_path(@client), class:"btn btn-primary" %> |
  <%= link_to 'Back', clients_path, class:"btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecruitBot</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>

    <!-- Custom styles for this template-->
    <link href="/css/sb-admin-2.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <%= render "layouts/partials/sidebar" %>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <%= render "layouts/partials/topbar" %>
                
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; RecruitBot2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Custom scripts for all pages-->
    <script src="/js/sb-admin-2.js"></script>

</body>

</html>

app/views/layouts/partials/_logout.html.erb
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

app/views/layouts/partials/_sidebar.html.erb
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

            <li class="nav-item">
                <a class="nav-link" href="/">
                <img class="rounded-square"
                    src="/img/StockMarket.jpg">
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            
            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Pages Collapse Menu -->
            <% if current_user %>
            <li class="nav-item">

                <% if current_user.role == 'Admin' %>
                    <a class="nav-link" href="/users">
                        <i class="fas fa-fw fa-users"></i>
                        <span>Users</span></a>
                     <a class="nav-link" href="/clients">
                        <i class="fas fa-fw fa-users"></i>
                        <span>Clients</span></a>
                <% else %>
                    <a class="nav-link" href="<%= user_path(current_user) %>">
                        <i class="fas fa-fw fa-user"></i>
                        <span>Profile</span></a>
                <% end %>

                <a class="nav-link" href="/actions">
                    <i class="fas fa-fw fa-chart-bar"></i>
                    <span>Actions</span></a>
            
                <a class="nav-link" href="/messages">
                    <i class="fas fa-fw fa-chart-bar"></i>
                    <span>Messsages</span></a>
            
                <a class="nav-link" href="/positions">
                    <i class="fas fa-fw fa-dollar-sign"></i>
                    <span>QnA</span></a>

            
                <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete">
                    <i class="fas fa-fw fa-sign-out-alt"></i>
                    <span>Sign Out</span></a>

            </li>
            <% else %>
            <li class="nav-item">

                <a class="nav-link" href="<%= new_user_session_path %>" >
                    <i class="fas fa-fw fa-sign-in-alt"></i>
                    <span>Sign In</span></a>

            </li>
            <% end %>


        </ul>
        <!-- End of Sidebar -->

app/views/layouts/partials/_topbar.html.erb
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form action="/<%=@search_controller%>/search"
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" name="query" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">


                        <% if current_user %>
                        <li class="nav-item dropdown no-arrow">

                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <% if current_user %>
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.full_name %></span>
                                <span id="current_user_id" data-current-user-id="<%=current_user.id%>">
                                <% end %>
                                <img class="img-profile rounded-circle"
                                    src="/img/undraw_profile.svg">
                            </a>
                        
                        </li>

                        <% end %>

                    </ul>

                </nav>
                <!-- End of Topbar -->

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Custom fonts for this template-->
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/css/sb-admin-2.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div>
                        <image class="print_header" src="/img/StockMarket.jpg">
                    </div>
                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->


        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <script> window.print() </script>

</body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= form.label :role %>
    <%= form.text_field :role, class: "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= form.label :client_id %>
    <%= form.number_field :client_id, class: "form-control" %>
  </div>


<button type="submit" class="btn btn-primary">Save</button>

<% end %>

app/views/users/edit.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Editing User</h1>
</div>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice" class="alert" role="alert"><%= notice %></p>

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Users</h1>
    <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
</div>


<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Role</th>
      <th>Client</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.role %></td>
        <td><%= user.client.name if user.client %></td>
        <td>
          <%= link_to 'Show', user, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary" %>
          <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">New User</h1>
</div>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-striped">



<tr>
  <td>
    <strong>First name:</strong>
  </td>
  <td>
          <%= @user.first_name %>
      </td>
</tr>


<tr>
  <td>
    <strong>Last name:</strong>
  </td>
  <td>
          <%= @user.last_name %>
      </td>
</tr>


<tr>
  <td>
    <strong>Role:</strong>
  </td>
  <td>
          <%= @user.role %>
      </td>
</tr>


<tr>
  <td>
    <strong>Client:</strong>
  </td>
  <td>
          <%= @user.client.name if @user.client %>
      </td>
</tr>


</table> 

<div class="action">
  <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-primary" %> |
  <%= link_to 'Back', users_path, class:"btn btn-primary" %>
</div>